### PR TITLE
WIP - User settings sidebar menu

### PR DESCRIPTION
**Pull request by camjackson**
This is a work in progress for #411, as well as other issues that need the user settings menu.

The styling is still wrong, just wanted to open this to get feedback on whether we've put everything in totally the wrong place etc :)

cc: @phazel, who worked on this too.

### CODE REVIEW

**Comment by kaeff** [comment]
It seems you've run into one of our flaky FTs - we're having problems with checkboxes.feature's 'when I delete the mail' step locally, too. 

I've retriggered the pipeline for this PR to try again.

**Comment by bwagnerr** [comment]
@camjackson I like the idea and it seems everything is kinda in place although I noticed you only have the visual part currently, if you add some logic, please try to add tests too, they are quite easy to write with flightjs :)

Also when you begin firing and listening to events, try to remember that components optimally don't know each other, so the events should show intention instead of ordering another component to do something (like "i want to show mail x" instead of "mail view open mail x" mentality).

**Comment by camjackson** [comment]
This is still WIP. In order to make the user settings box not be hidden behind the main panel, I've given the left nav bar a higher z-index. I then had to do some more css stuff to make the hide/show toggle work again.

Stuff still left to do:

* Fix the show/hide toggle animation
* User settings box is still hidden, but now because of overflow rather than z-index (I think).
* The bottom buttons aren't in the bottom any more
* The little arrow on the left of the settings box
* Positioning and width of the settings box probably need to be smarter, depending on content
* User's email is still hardcoded to mine

@rdoh

**Comment by giovaneliberato** [comment]
Hey @camjackson, the build failed due to some jshint errors. You can run this verification with `./go jshint` on web-ui folder.

The issue #476 should prevent this :D

**Comment by camjackson** [comment]
Closing this, going to open another shortly...

**Pull request closed without merging**
