### PR TITLE
Adds portuguese translation for i18n tags

### PR DESCRIPTION
**Pull request by cacarrara**
This change only translate the current existing tags. It doesn't deal
with places where tags isn't used nor nonexistent tags. #540

### CODE REVIEW

**Comment by giovaneliberato** [comment]
@cacarrara Thanks for your PR! I', reviewing it

**Comment by giovaneliberato** [comment]
On the "front page" there's just 2 places where the translation isn't working. I'll accept and fix this

screen shot 2016-02-17 at 2 35 09 pm

**Comment by giovaneliberato** [comment]
ops, sorry for closing without merging :p

**Comment by cacarrara** [comment]
@giovaneliberato thanks for merging. About the places where translations isn't working, I've talked with @bwagnerr on IRC and he told that some places aren't using i18n tags. This may be the problem you found. I don't know if it's appropriate, but we could open an issue to review the tags utilization to track this work.

**Pull request merged**
