### PR TITLE
Transition from require to webpack

### PR DESCRIPTION
**Pull request by anikarni**
This pull request starts the transition from requirejs to webpack. It removes all requirejs configurations and updates how the compilation of javascript files was being done. Here's what the transition includes and what has been done:

- [x] Delete config/package.sh, which was minifying and grouping files through bash commands
- [x] Create a new entry file and sets both index.js and sandbox.js as entry points for creating bundles
- [x] It now only serves files from the dist folder, so files are served locally as they would in production environments, separating clearly our source code from compiled code
- [ ] Make tests independent of require
- [ ] Remove require.js as a dependency (after updating tests)
- [ ] Use webpack-dev-server to serve files locally, which allows for hot-reloading on change
- [ ] Change the syntax for how files are imported inside javascript code
- [ ] Add loader for handlebars and updates how we deal with these templates
- [ ] Add loader for sass and removes compass
- [ ] Move all dependencies to npm and delete bower
- [ ] Update dependencies on outdated libraries that require global variables to work so they can be added in bundle (e.g. foundation)
- [ ] Update code to use es6 (a continuous task)

That's what I can think of to do right now, but there will probably be more in the future.

### CODE REVIEW

**Comment by bwagnerr** [comment]
This will be beautiful! I'll take a better look as soon as I can :)

**Comment by bwagnerr** [comment]
Just to note, to avoid problems with deployment, make sure the files and directories (dist for example) are being included on the debian folder, I'll check that also

**Comment by tuliocasagrande** [comment]
@anikarni I think this is the file @bwagnerr talked about: https://github.com/pixelated/pixelated-user-agent/blob/master/service/MANIFEST.in

**Comment by anikarni** [comment]
@tuliocasagrande , yeah, I'm not entirely sure how that works. It makes sense to me that I should include it in they debian packages, but I'm assuming someone else takes care of js files, because they aren't there and they get included. In fact, they were already packaged to the dist folder, so I'm still not seeing if anything needs to be changed. But maybe I'm missing something. That's why I really wanted to try going through the pipeline. It's very likely something will fail, but I want to be here tomorrow to make sure I can fix it. Does that make sense? Is there anything else you see that needs to be changed?

**Pull request merged**
