### PR TITLE
show user email address in title

### PR DESCRIPTION
**Pull request by sw00**
Exposing email address to be shown in title.

### CODE REVIEW

**Comment by sw00** [comment]
My test is breaking but I'm not sure what I'm missing.

**Comment by bwagnerr** [comment]
Hey, I think the problem was unrelated and is fixed now, could you try rebasing the latest changes and running the tests again?

**Comment by rdoh** [comment]
I've tested rebasing this with the latestchanges. I see the following error in one of the service unit tests -- is this what you were talking about @sw00 ? The tests hang after outputting this message.

 "IOError: Invalid certificate file: /home/vagrant/.config/leap/events/zmq_certificates/public_keys/server.key" 

There's no server.key at that path, but that's the case regardless of whether I have sw00's changes or not, and without the changes, the tests pass. 

I don't understand why this commit has introduced a dependency on having a server.key there.

But then again, I don't know what that server.key is even for.

**Comment by sw00** [comment]
`/home/vagrant/.config/leap/events/zmq_certificates/public_keys/server.key` get's removed as part of running `./go test`.

Test is probably failing because I have mocked out a component in `root_resource.initialize()` that is required to recreate `server.key`.

I haven't had much time this week to work on this PR, will look at it once get a chance. It looks like I'll need to tweak the integration tests as well, so it's a bit more work than initially expected.

**Comment by sw00** [comment]
I could not avoid the "invalid certificate file" issue with any amount of mocking KeyManager so I had to remove execution of `root_resource.initialize(...)` in the test.

Not ideal, but I think adequate for this feature.

**Comment by bwagnerr** [comment]
Looks good, just verified this, everything is working, the tests passed and the functionality is there.

Merging, thanks!

**Pull request merged**
