### PR TITLE
added note about credentials config file

### PR DESCRIPTION
**Pull request by thokari**

### CODE REVIEW

**Comment by thokari** [comment]
How can this fail, I just changed the README.md and .gitignore?
Is it maybe somehow related to https://github.com/pixelated/pixelated-user-agent/issues/571?

**Comment by giovaneliberato** [comment]
@thokari the snap CI is kinda flaky theses days. The build timed out. I'll re-run rhis.. Btw, thank you for the PR :D

**Comment by fbernitt** [comment]
Hey, error message says it could "not load PhantomJS"

```
16 02 2016 18:11:41.791:WARN [launcher]: Can not load "PhantomJS", it is not registered!
  Perhaps you are missing some plugin?
```

We'll have a look

**Comment by fbernitt** [comment]
Test is green now.

**Comment by fbernitt** [comment]
About the change, I would prefer to move that a little bit down and not have it in the initial getting started steps. We could move it down to 'Further Notes' and just add a hint to that part to the getting started guide?

**Comment by thokari** [comment]
@fbernitt I agree, will update my pull request shortly.

**Comment by felixhammerl** [comment]
Sorry, I didn't see your PR when I added two example config files `try.alice.ini` and `try.bob.ini`, see https://github.com/pixelated/pixelated-user-agent/commit/f3cf19b
Do you wanna include the pointers to those files?

**Comment by thokari** [comment]
I've updated the PR. I used git rebase, but still have a merge commit for some reason... Let me know if that works now, Else just delete this, and I will update the README directly...

**Comment by felixhammerl** [comment]
sorry for the late response... if you can cherry-pick your commits onto the current master, that'd be helpful and get rid of the merge commit.

**Comment by thokari** [comment]
Continued here: https://github.com/pixelated/pixelated-user-agent/pull/633

**Pull request closed without merging**
