### PR TITLE
pinned message header in read mode

### PR DESCRIPTION
**Pull request by thokari**
Reopening after clean rebase

### CODE REVIEW

**Comment by thokari** [comment]
The issue is more complicated that I thought, I have to dig into the whole structure of the HTML and CSS a bit more. I also noticed that although the responsive columns are extensively used, the layout still kind of breaks on medium and small screens, see screenshot (the bar on the left collapses more than it should). I'll take a look at it tomorrow!
responsive_bug

**Comment by felixhammerl** [comment]
RE responsiveness: I agree that there is a heap of technical debt hidden in the markup and stylesheets. The issue you're pointing to is discussed in this ticket: https://github.com/pixelated/pixelated-user-agent/issues/620

**Comment by felixhammerl** [comment]
for future reference: 
this thing breaks on a layout <= 1024px. i'll still be merging it, for the following reasons: the only device with 1024 px horizontal resolution these days will be a tablet, and we don't have a mobile/tablet UI anyway (yet).

**Comment by felixhammerl** [comment]
One more thing: The integration tests fail because the date and the dropdown menu are no longer present. Check the screenshots (circled red). Can you fix that?

screen shot 2016-02-23 at 12 45 07 pm
screen shot 2016-02-23 at 12 43 27 pm

**Comment by thokari** [comment]
@felixhammerl Yes I noticed that, and I am trying to fix it, however the problem is that when setting the header to "position: fixed", which to my knowledge is the only way to have it stick at the top, then it is very hard to know what width it should have, especially because there is the collapsible menu on the left, which requires that to change dynamically. And the default width has it go off the screen. I don't know how to solve this in a clean way. In order to have this work now, I will use a width that is small enough, so that the buttons stay on screen for every size, but it will look ugly...

**Comment by thokari** [comment]
So now the problem is that the mail action buttons move off screen, when the left menu is expanded.

**Comment by felixhammerl** [comment]
maybe it's worth taking a look at the changes coming to the master soon: https://github.com/pixelated/pixelated-user-agent/tree/dev/sandbox

**Comment by felixhammerl** [comment]
There were substantial changes to the stylesheets, hence this PR is outdated. I'll close it for now...

**Pull request closed without merging**
