### PR TITLE
Determine user's configured shell then set variable accordingly. #624 @jnews0n / kafkas_sonnet

### PR DESCRIPTION
**Pull request by jnews0n**
Also added a test to ensure the run-time platform is OSX.

### CODE REVIEW

**Comment by felixhammerl** [comment]
can someone with zsh do QA on this? e.g. @fbernitt or @mnandri

**Comment by jeffhsta** [comment]
I have ZSH, but I am running linux, I tested some commands on OSX, and it seems work fine.

Can some QA it on ZSH just to make sure?

**Comment by deniscostadsc** [comment]
Hi @jnews0n, as you can see at https://github.com/pixelated/pixelated-user-agent/pull/628, I also tried to solve this problem. I was in a hacknight. I tried do it in a easy way but I failed :hankey:.

You code does a few verification, but I think you have to do some changes in order to have you PR merge. I'm going to list them here:

* The shebang should remain *#!/bin/bash*. I know that *env* makes scripts more platform independent, but bash is ever in */bin*. So in this case you don't need to changes this. In Python scripts, for instance, this makes a lot of sense.

* To check is system is OSX you could simplify your code doing something like this:
```bash
if [ $(uname) == "Darwin" ]
then
    echo "You are not in a OSX system!"
    exit 1
fi
```

* To check what shell is running I think you can do something like this:
```bash
function get_current_shell {
    case $SHELL in
        *bash)
            echo ~/.bash_profile
        ;;
        *zsh)
            echo ~/.zchrc
        ;;
        # If there is more shell just put them here
    esac
}
...
echo "export PATH=$PATH:~/.rbenv/versions/2.2.3/bin" >> $(get_current_shell)
```

* You indented the calls to "install_rbenv" and others functions. Removes this unnecessary indent.

* I know that the indentation in this file wasn't consistant, you could use the 4 spaces for indentation, and format the *ifs* like this:

```bash
if $condition
then
    comand
fi
```


Just change this and you PR will be merged as soon as I could.

Thank you for the help! :+1:

**Comment by jnews0n** [comment]
Can I confirm if the issue is to validate the user's _running_ shell or the user's _configured_ shell.  The distinction whilst pedantic, I think determines the routine used, i.e. from a user $var or from a system configuration item check.  The former assumes the user hasn't spawned a shell, the latter assumes the user's configured state is the target.

**Comment by deniscostadsc** [comment]
The issue is to append "export PATH=$PATH:~/.rbenv/versions/2.2.3/bin" to rcfile of the current shell running.

You need to check which shell is running in order to get correct rcfile.

**Comment by jnews0n** [comment]
I think I phrased my question poorly. 
The last part of your response is the crux of my question. 

Is the running shell the correct shell or the configured shell the correct shell?


Cheers,

Jon
---

**Comment by deniscostadsc** [comment]
> Is the running shell the correct shell or the configured shell the correct shell?

The running shell.

**Comment by deniscostadsc** [comment]
I think those failing tests aren't related to @jnews0n changes. Can someone confirm this?

**Comment by giovaneliberato** [comment]
Not sure about the errors on SNAP. I downloaded the code on my machine and everything is working well. Does anyone have a guess?

**Comment by giovaneliberato** [comment]
This may be a very dummy guess, but is it related to Feb 29th and snap wasn't expecting that? :p

**Comment by deniscostadsc** [comment]
@jnews0n I said to get the value from $SHELL variable, but this is not going to work.

* First of all, every time this script is run, it is bash. because of the shebang (#!/bin/bash).
* If you remove it, sh is going to run instead of bash.

So you need to change the aproach. Check if the rcfile is present, not the running shell. if zshrc, echo it.

One more thing. You are formatting your code with tabs, use 4 spaces.

If you have any doubt. please reach me here.

Regards :+1:

**Comment by jnews0n** [comment]
Indentation aside, my original approach would have dealt with all of these issues wouldn't it?


Cheers,

Jon
---

**Comment by deniscostadsc** [comment]
> Indentation aside, my original approach would have dealt with all of these issues wouldn't it?

I think a aproach like this would be more legible and easier (I didn't run this code). And you can still use a function in the same way you did.

```bash
function get_rcfile {
    [ -f ~/.zshrc ] && echo ~/.zshrc && return 0
    [ -f ~/.bash_profile ] && echo ~/.bash_profile && return 0
    echo "Your shell is not supported yet" && exit 1
}
```
What do you think?

**Comment by jnews0n** [comment]
But that doesn't tell us what shell the user is running or is configured to run. 

Eg if a user has chsh -s $some-other-shell then the .rc file will not be created. There will therefore be a dissonance between the users configuration and their running environment. 




Cheers,

Jon
---

**Comment by deniscostadsc** [comment]
> But that doesn't tell us what shell the user is running or is configured to run.

`dscl . -read ~ UserShell` could do the job to get the shell configured to run. But there is no easy way to get rcfile configured to be load at startup. It would be nice if was just get shell name and concatenate with "rc", but that is not true. You have to check it manually.

> Eg if a user has chsh -s $some-other-shell then the .rc file will not be created. There will therefore be a dissonance between the users configuration and their running environment.

In this case you have to check for all common rcfiles. If the user changes his shell, he'll have to run the setup script again.

So, I think this brute force check bellow still the best way to solve the problem.

```bash
function get_rcfile {
    [ -f ~/.zshrc ] && echo ~/.zshrc && return 0
    ...
```

Can you think in a better way?


Regards

**Comment by jnews0n** [comment]
so far I have established the following for Darwin / OSX:
1) /bin/bash is default which sources .bash_profile
2) If a user changes to zsh, either manually as a forked shell or configured by chsh -s /bin/zsh, and ~/.zshrc does not exist then ~/.profile will be sourced.
3) This does not apply for /bin/tcsh.
4) ksh reads from ~/.profile

This suggests that concatenating the $vars to ~.profile, regardless of how either the bash, ksh, sh or zsh shells are invoked may avoid having to test for and handle conditions for each of the shells in /etc/shells.

An alternative:  I don't have my head around the rest of the codebase yet, but could we store the environment for the rest of the setup by creating a ~/.pixelated_vars?

**Comment by jnews0n** [comment]
Let's see how this goes...

**Comment by deniscostadsc** [comment]
I think the code is OK!

But why you changed those files?
```
service/test/unit/resources/test_logout_resources.py
service/pixelated/resources/logout_resource.py
```

**Comment by jnews0n** [comment]
Maybe my git pull rebase was off. I know I didn't edit those files. 


Cheers,

Jon
---

**Comment by deniscostadsc** [comment]
Those lines are repeated.

```bash
echo "export PATH=$PATH:~/.rbenv/versions/2.2.3/bin" >> $(current_shell)
echo 'eval "$(rbenv init -)"' >> $(current_shell)
echo "export PATH=$PATH:~/.rbenv/versions/2.2.3/bin" >> $(current_shell)
echo 'eval "$(rbenv init -)"' >> $(current_shell)
```

**Comment by deniscostadsc** [comment]
Thanx @jnews0n.

**Pull request merged**
